# Changes here will be overwritten by Copier
_commit: v0.2.5
_src_path: gh:ninanor/python-template
author_name: ninanor
debug: false
default_branch_name: main
docker: false
email: niccolo.cantu@nina.no
notebook: false
project_name: NVA Sync
project_slug: nva_sync
repo_name: nva_sync
repo_org: ninanor
template_type: python
type_annotations: false
